import './bootstrap';
require('./bootstrap');
window.Vue = require('vue');

Vue.component('beasiswa-detail', require('./components/BeasiswaDetail.vue').default);

const app = new Vue({
    el: '#app',
});


import React from 'react';
import ReactDOM from 'react-dom';
import FilterBeasiswa from './components/FilterBeasiswa';

// Assume these are fetched or passed from your Laravel backend.
const tingkatStudi = [
{ id: 1, nama: 'S1' },
{ id: 2, nama: 'S2' },
{ id: 3, nama: 'S3' },
{ id: 4, nama: 'Diploma' }
// Add more items as needed
];

const negara = [
    { id: 1, nama: 'Afghanistan' },
    { id: 2, nama: 'Albania' },
    { id: 3, nama: 'Algeria' },
    { id: 4, nama: 'Andorra' },
    { id: 5, nama: 'Angola' },
    { id: 6, nama: 'Antigua and Barbuda' },
    { id: 7, nama: 'Argentina' },
    { id: 9, nama: 'Australia' },
    { id: 10, nama: 'Austria' },
    { id: 11, nama: 'Azerbaijan' },
    { id: 12, nama: 'Bahamas' },
    { id: 13, nama: 'Bahrain' },
    { id: 14, nama: 'Bangladesh' },
    { id: 15, nama: 'Barbados' },
    { id: 16, nama: 'Belarus' },
    { id: 17, nama: 'Belgium' },
    { id: 18, nama: 'Belize' },
    { id: 19, nama: 'Benin' },
    { id: 20, nama: 'Bhutan' },
    { id: 21, nama: 'Bolivia' },
    { id: 22, nama: 'Bosnia and Herzegovina' },
    { id: 23, nama: 'Botswana' },
    { id: 24, nama: 'Brazil' },
    { id: 25, nama: 'Brunei' },
    { id: 26, nama: 'Bulgaria' },
    { id: 27, nama: 'Burkina Faso' },
    { id: 28, nama: 'Burundi' },
    { id: 29, nama: 'Cambodia' },
    { id: 30, nama: 'Cameroon' },
    { id: 31, nama: 'Canada' },
    { id: 32, nama: 'Cape Verde' },
    { id: 33, nama: 'Central African Republic' },
    { id: 34, nama: 'Chad' },
    { id: 35, nama: 'Chile' },
    { id: 36, nama: 'China' },
    { id: 37, nama: 'Colombia' },
    { id: 38, nama: 'Comoros' },
    { id: 39, nama: 'Costa Rica' },
    { id: 40, nama: 'Croatia' },
    { id: 41, nama: 'Cuba' },
    { id: 42, nama: 'Cyprus' },
    { id: 43, nama: 'Czech Republic' },
    { id: 44, nama: 'Democratic Republic of the Congo' },
    { id: 45, nama: 'Denmark' },
    { id: 46, nama: 'Djibouti' },
    { id: 47, nama: 'Dominica' },
    { id: 48, nama: 'Dominican Republic' },
    { id: 49, nama: 'East Timor' },
    { id: 50, nama: 'Ecuador' },
    { id: 51, nama: 'Egypt' },
    { id: 52, nama: 'El Salvador' },
    { id: 53, nama: 'Equatorial Guinea' },
    { id: 54, nama: 'Eritrea' },
    { id: 55, nama: 'Estonia' },
    { id: 56, nama: 'Eswatini' },
    { id: 57, nama: 'Ethiopia' },
    { id: 58, nama: 'Fiji' },
    { id: 59, nama: 'Finland' },
    { id: 60, nama: 'France' },
    { id: 61, nama: 'Gabon' },
    { id: 62, nama: 'Gambia' },
    { id: 63, nama: 'Georgia' },
    { id: 64, nama: 'Germany' },
    { id: 65, nama: 'Ghana' },
    { id: 66, nama: 'Greece' },
    { id: 67, nama: 'Grenada' },
    { id: 68, nama: 'Guatemala' },
    { id: 69, nama: 'Guinea' },
    { id: 70, nama: 'Guinea-Bissau' },
    { id: 71, nama: 'Guyana' },
    { id: 72, nama: 'Haiti' },
    { id: 73, nama: 'Honduras' },
    { id: 74, nama: 'Hungary' },
    { id: 75, nama: 'Iceland' },
    { id: 76, nama: 'India' },
    { id: 77, nama: 'Indonesia' },
    { id: 78, nama: 'Iran' },
    { id: 79, nama: 'Iraq' },
    { id: 80, nama: 'Ireland' },
    { id: 81, nama: 'Israel' },
    { id: 82, nama: 'Italy' },
    { id: 83, nama: 'Ivory Coast' },
    { id: 84, nama: 'Jamaica' },
    { id: 85, nama: 'Japan' },
    { id: 86, nama: 'Jordan' },
    { id: 87, nama: 'Kazakhstan' },
    { id: 88, nama: 'Kenya' },
    { id: 89, nama: 'Kiribati' },
    { id: 90, nama: 'Kuwait' },
    { id: 91, nama: 'Kyrgyzstan' },
    { id: 92, nama: 'Laos' },
    { id: 93, nama: 'Latvia' },
    { id: 94, nama: 'Lebanon' },
    { id: 95, nama: 'Lesotho' },
    { id: 96, nama: 'Liberia' },
    { id: 97, nama: 'Libya' },
    { id: 98, nama: 'Liechtenstein' },
    { id: 99, nama: 'Lithuania' },
    { id: 100, nama: 'Luxembourg' },
    { id: 101, nama: 'Madagascar' },
    { id: 102, nama: 'Malawi' },
    { id: 103, nama: 'Malaysia' },
    { id: 104, nama: 'Maldives' },
    { id: 105, nama: 'Mali' },
    { id: 106, nama: 'Malta' },
    { id: 107, nama: 'Marshall Islands' },
    { id: 108, nama: 'Mauritania' },
    { id: 109, nama: 'Mauritius' },
    { id: 110, nama: 'Mexico' },
    { id: 111, nama: 'Micronesia' },
    { id: 112, nama: 'Moldova' },
    { id: 113, nama: 'Monaco' },
    { id: 114, nama: 'Mongolia' },
    { id: 115, nama: 'Montenegro' },
    { id: 116, nama: 'Morocco' },
    { id: 117, nama: 'Mozambique' },
    { id: 118, nama: 'Myanmar' },
    { id: 119, nama: 'Namibia' },
    { id: 120, nama: 'Nauru' },
    { id: 121, nama: 'Nepal' },
    { id: 122, nama: 'Netherlands' },
    { id: 123, nama: 'New Zealand' },
    { id: 124, nama: 'Nicaragua' },
    { id: 125, nama: 'Niger' },
    { id: 126, nama: 'Nigeria' },
    { id: 127, nama: 'North Korea' },
    { id: 128, nama: 'North Macedonia' },
    { id: 129, nama: 'Norway' },
    { id: 130, nama: 'Oman' },
    { id: 131, nama: 'Pakistan' },
    { id: 132, nama: 'Palau' },
    { id: 133, nama: 'Palestine' },
    { id: 134, nama: 'Panama' },
    { id: 135, nama: 'Papua New Guinea' },
    { id: 136, nama: 'Paraguay' },
    { id: 137, nama: 'Peru' },
    { id: 138, nama: 'Philippines' },
    { id: 139, nama: 'Poland' },
    { id: 140, nama: 'Portugal' },
    { id: 141, nama: 'Qatar' },
    { id: 142, nama: 'Republic of the Congo' },
    { id: 143, nama: 'Romania' },
    { id: 144, nama: 'Russia' },
    { id: 145, nama: 'Rwanda' },
    { id: 146, nama: 'Saint Kitts and Nevis' },
    { id: 147, nama: 'Saint Lucia' },
    { id: 148, nama: 'Saint Vincent and the Grenadines' },
    { id: 149, nama: 'Samoa' },
    { id: 150, nama: 'San Marino' },
    { id: 151, nama: 'Sao Tome and Principe' },
    { id: 152, nama: 'Saudi Arabia' },
    { id: 153, nama: 'Senegal' },
    { id: 154, nama: 'Serbia' },
    { id: 155, nama: 'Seychelles' },
    { id: 156, nama: 'Sierra Leone' },
    { id: 157, nama: 'Singapore' },
    { id: 158, nama: 'Slovakia' },
    { id: 159, nama: 'Slovenia' },
    { id: 160, nama: 'Solomon Islands' },
    { id: 161, nama: 'Somalia' },
    { id: 162, nama: 'South Africa' },
    { id: 163, nama: 'South Korea' },
    { id: 164, nama: 'South Sudan' },
    { id: 165, nama: 'Spain' },
    { id: 166, nama: 'Sri Lanka' },
    { id: 167, nama: 'Sudan' },
    { id: 168, nama: 'Suriname' },
    { id: 169, nama: 'Sweden' },
    { id: 170, nama: 'Switzerland' },
    { id: 171, nama: 'Syria' },
    { id: 172, nama: 'Taiwan' },
    { id: 173, nama: 'Tajikistan' },
    { id: 174, nama: 'Tanzania' },
    { id: 175, nama: 'Thailand' },
    { id: 176, nama: 'Togo' },
    { id: 177, nama: 'Tonga' },
    { id: 178, nama: 'Trinidad and Tobago' },
    { id: 179, nama: 'Tunisia' },
    { id: 180, nama: 'Turkey' },
    { id: 181, nama: 'Turkmenistan' },
    { id: 182, nama: 'Tuvalu' },
    { id: 183, nama: 'Uganda' },
    { id: 184, nama: 'Ukraine' },
    { id: 185, nama: 'United Arab Emirates' },
    { id: 186, nama: 'United Kingdom' },
    { id: 187, nama: 'United States' },
    { id: 188, nama: 'Uruguay' },
    { id: 189, nama: 'Uzbekistan' },
    { id: 190, nama: 'Vanuatu' },
    { id: 191, nama: 'Vatican City' },
    { id: 192, nama: 'Venezuela' },
    { id: 193, nama: 'Vietnam' },
    { id: 194, nama: 'Yemen' },
    { id: 195, nama: 'Zambia' },
    { id: 196, nama: 'Zimbabwe' }
];

if (document.getElementById('react-root')) {
ReactDOM.render(<FilterBeasiswa tingkatStudi={tingkatStudi} negara={negara} />, document.getElementById('react-root'));
}
